# Generated by Django 3.0.6 on 2020-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.CharField(max_length=10)),
                ('Registeras', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=30)),
                ('password1', models.CharField(max_length=12)),
                ('password2', models.CharField(max_length=12)),
            ],
        ),
    ]
