# Generated by Django 3.0.6 on 2020-05-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.CharField(max_length=10)),
                ('Registeras', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
