# Generated by Django 3.0.6 on 2020-05-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
