# Generated by Django 3.0.6 on 2020-05-24 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_auto_20200524_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(max_length=200)),
                ('Disease', models.TextField(max_length=50)),
                ('Docname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Patname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Patient')),
            ],
        ),
    ]
