# Generated by Django 3.0.6 on 2020-05-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200525_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Registeras',
            field=models.CharField(choices=[('Select', '...'), ('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=30, null=True),
        ),
    ]
