# Generated by Django 3.0.6 on 2020-05-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20200525_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Registeras',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=30, null=True),
        ),
    ]
