# Generated by Django 3.0.6 on 2020-05-25 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_auto_20200525_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Department',
            field=models.CharField(default='Doctor', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Salary',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
