# Generated by Django 3.0.6 on 2020-05-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20200525_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Attendance',
            field=models.IntegerField(default=0),
        ),
    ]
