# Generated by Django 3.0.6 on 2020-05-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_doctor_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='BloodType',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
