# Generated by Django 3.0.6 on 2020-05-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20200528_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
