# Generated by Django 2.2.1 on 2020-05-28 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20200528_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='Docname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Doctor'),
        ),
    ]
