# Generated by Django 3.0.6 on 2020-06-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Address',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='BloodType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Department',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
